version: '3.9'
services:
  postgres-dev:
    env_file:
      - .env.dev
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data/dev:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  postgres-prod:
    env_file:
      - .env.prod
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data/prod:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  server-dev:
    env_file:
      - .env.dev
    build:
      context: .
    volumes:
      - /etc/letsencrypt/live/bump-project.o-r.kr:/etc/letsencrypt/live/bump-project.o-r.kr:ro
      - /etc/letsencrypt/archive/bump-project.o-r.kr:/etc/letsencrypt/archive/bump-project.o-r.kr:ro
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-dev:5432/${POSTGRES_DB}
    depends_on:
      - postgres-dev
    ports:
      - '3001:3000'

  server-prod:
    env_file:
      - .env.prod
    build:
      context: .
    volumes:
      - /etc/letsencrypt/live/bump-project.o-r.kr:/etc/letsencrypt/live/bump-project.o-r.kr:ro
      - /etc/letsencrypt/archive/bump-project.o-r.kr:/etc/letsencrypt/archive/bump-project.o-r.kr:ro
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-prod:5432/${POSTGRES_DB}
    depends_on:
      - postgres-prod
    ports:
      - '3000:3000'

volumes:
  pgdata_dev:
  pgdata_prod:
